### PR TITLE
Redux login&register

### LINKED ISSUE #42: Add redux for the login and registration
Adde state, actions, and reducer for the login and registration and integrate with the backend

### PR DESCRIPTION
**Pull request by Hemanth759**
Added the redux functionality to the login and register pages in the flutter application

### CODE REVIEW

**Comment by sriram012** [comment]
> Added the redux functionality to the login and register pages in the flutter application

wasn't it already added?

**Comment by Hemanth759** [comment]
Nope.... Not to the master branch

**Comment by Hemanth759** [comment]
@sriram012 can you please review and accept approve the merging

**Review by sriram012 — APPROVED** [review]
All good.

**Pull request merged**
